server:
  port: 8080
   
  
spring: 
  application:
      name: Api-Gateway
  cloud:
      gateway:
         routes:
         - id: Guest-Microservice
           uri: http://localhost:8083/
           predicates:
             - Path=/guest/**
           
         - id: Room-Microservice
           uri: http://localhost:8082/
           predicates:
             - Path=/room/**
           
         - id: Inventory-Microservice
           uri: http://localhost:8081/
           predicates:
             - Path=/inventory/**

         - id: Reservation-Microservice
           uri: http://localhost:8084/
           predicates:
             - Path=/reservation/**

         - id: user-service
           uri: http://localhost:8091/
           predicates:
             - Path=/**
             
             
             
             